#!/bin/bash

JOBS=1

while getopts "j:" opt; do
    case "${opt}" in
        j)
            JOBS=${OPTARG}
            ;;
        *)
			exit 1
            ;;
    esac
done
shift $((OPTIND-1))

echorun() {
	echo $@
	$@
}

cd bash
autoreconf -if
echorun ./configure --disable-readline --disable-history --disable-bang-history --disable-progcomp $@
echorun make -j${JOBS} libbash.a
